### ISSUE TITLE
can we get the error code returned when an error occurs?

### ISSUE THREAD

**Issue by lfxc** [arodygin/php-linode-api3#4]
https://www.linode.com/api#error_codes

would like to move away from relying on the error message and rely on codes. 

thanks!

**Comment by arodygin** [comment]
In case of errors the library raises LinodeException, where error code is set to the exception code. So, you can wrap your calls into try-catch blocks like below:

```php
use Linode\LinodeApi;
use Linode\LinodeException;
use Linode\PaymentTerm;

// Create new linode.
try {
    $api = new LinodeApi('tbd');
    $res = $api->create(3, 1, PaymentTerm::ONE_MONTH);

    printf("Linode #%d has been created.\n", $res['LinodeID']);
}
catch (LinodeException $e) {
    printf("Error #%d: %s.\n", $e->getCode(), $e->getMessage());
}
```

I have also updated the project's [README](https://github.com/arodygin/php-linode-api3/blob/master/README.md). Please let me know whether it helps.

**Comment by lfxc** [comment]
perfect!  thank you and please continue the great work!

**Comment by arodygin** [comment]
Happy to help!
